import pandas as pd
import os
import tkinter as tk
from tkinter import filedialog, messagebox

def csv_to_adif(csv_file):
    # Create the ADIF filename (same as CSV but with .adi extension)
    adif_file = os.path.splitext(csv_file)[0] + ".adi"

    # Read CSV file
    df = pd.read_csv(csv_file)

    # Open ADIF file for writing
    with open(adif_file, "w", encoding="utf-8") as f:
        f.write("Generated by CSV to ADIF Converter\n<EOH>\n")  # ADIF header

        for _, row in df.iterrows():
            adif_entry = ""
            for col, value in row.items():
                if pd.notna(value):  # Ignore NaN values
                    adif_entry += f"<{col.upper()}:{len(str(value))}>{value} "
            adif_entry += "<EOR>\n"  # End of record
            f.write(adif_entry)

    messagebox.showinfo("Conversion Complete", f"ADIF file saved as:\n{adif_file}")

def select_file():
    file_path = filedialog.askopenfilename(
        title="Select CSV File",
        filetypes=[("CSV Files", "*.csv")]
    )
    if file_path:
        csv_to_adif(file_path)

# Create GUI
root = tk.Tk()
root.title("CSV to ADIF Converter")
root.geometry("300x150")

label = tk.Label(root, text="Select a CSV file to convert:", font=("Arial", 12))
label.pack(pady=10)

button = tk.Button(root, text="Select CSV File", command=select_file, font=("Arial", 12))
button.pack(pady=10)

root.mainloop()